# Generated by Django 5.0.1 on 2024-02-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
