# Generated by Django 5.0.1 on 2024-01-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_parent_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news_images'),
        ),
    ]
